import "./styles/globals.css";

export const metadata = {
  title: "Portfolio - Sebastian Fok",
  description: "Computer generated by Sebastian Fok",
  icons: {
    
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" style={{ padding:"0", margin:"0" }}>
      <body>
        {children}
      </body>
    </html>
  );
}
