"use client";

import "./styles/globals.css"; 
import { usePathname } from "next/navigation";
import Navbar from "./components/navbar/page";

export const metadata = {
  title: "Portfolio - Sebastian Fok",
  description: "Computer generated by Sebastian Fok",
  icons:"/images/WhiteColour.svg"
};

export default function RootLayout({ children }) {
  const pathname = usePathname();

  const pageColors = {
    "/": "var(--white)",
    "/pages/3d": {bgColor: "var(--black)", navColor: "var(--white)"},
    "/pages/motion": {bgColor: "var(--black)", navColor: "var(--white)"},
    "/pages/visual": "var(--white)",
    "/pages/teamwork": "var(--white)"
  };

  const { bgColor, navColor } = pageStyles[pathname] || pageStyles["/"];

  return (
    <html lang="en" style={{ padding:"0", margin:"0" }}>
      <body style={{ backgroundColor: bgColor }}>
        <Navbar navColor={navColor} />
        {children}
      </body>
    </html>
  );
}