import { Inter } from 'next/font/google'
import './globals.css'

const inter =
Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next\nApp',
  description: 'Generated by create next app',
}

export default function\nRootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
