import "./styles/globals.css"; 
import ClientWrap from "./clientWrap";
// import { ViewTransitions } from "next-view-transitions";

export const metadata = {
  title: "Portfolio - Sebastian Fok",
  description: "Computer generated by Sebastian Fok",
  icons:"/media/logo/sebfoklogo.png"
};

export default function RootLayout({ children }) {
  return (
    // <ViewTransitions>
      <html lang="en" style={{ padding:"0", margin:"0" }}>
        <body suppressHydrationWarning={true}>
          <ClientWrap>{children}</ClientWrap>
        </body>
      </html>
    {/* </ViewTransitions> */}

  );
}