import "./styles/globals.css"; 
// import ClientWrap from "./clientWrap";

export const metadata = {
  title: "Portfolio - Sebastian Fok",
  description: "Computer generated by Sebastian Fok",
  icons:"/media/logo/WhiteColour.svg"
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" style={{ padding:"0", margin:"0" }}>
      <body suppressHydrationWarning={true}>
        {/* <ClientWrap>{children}</ClientWrap> */}
        {children}
      </body>
    </html>
  );
}